# Generated by Django 4.2.2 on 2023-06-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticaretSitesi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='not a category', on_delete=django.db.models.deletion.CASCADE, to='ticaretSitesi.category'),
            preserve_default=False,
        ),
    ]
